### ISSUE TITLE
python 3.5 compatebility issue

### ISSUE THREAD

**Issue by ToxidoLiu** [wolfib/image-classification-CIFAR10-tf#1]
if you run the _two_layer_fc.py_ in python 3.5 it will throw an error as
     <pre><code>Traceback (most recent call last):
  File "D:/workspace/python_dir/tf-image-recognition/run_fc_model.py", line 66, in <module>
    batch = next(batches)
  File "D:\workspace\python_dir\tf-image-recognition\data_helpers.py", line 71, in gen_batch
    index = len(data)
TypeError: len() of unsized object </code></pre> 

Please ignore the line number coz I've changed the code a little bit.  

And the error says the object created by zip() will no longer be 'Sized' so len() could not read its actual length. 
So I modified a little at
<pre><code>batches = data_helpers.gen_batch(list(zipped_data), FLAGS.batch_size, FLAGS.max_steps)</pre></code>    

That will do the trick.  

Really liked your blog, I've read about both of the _How to Build a Simple Image Recognition System with TensorFlow_  series, those have been of great help.  

Hope to see more. 
Thanks

**Comment by wolfib** [comment]
Thank you!

I've implemented your bugfix. Also modified a few other lines to make the code compatible with Python 3.5.

Thanks a lot for the feedback! Hearing that my stuff is useful to others makes me very happy.
